all: task.exe dump clean

dump:
	./task.exe

task.exe: main.o CRational.o
	g++ main.o CRational.o -o task.exe

main.o: main.cpp
	g++ -c main.cpp

CRational.o: CRational.cpp
	g++ -c CRational.cpp

clean:
	rm *.o task.exe